[project]
name = "prog-5-j2-tp2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.122.0",
    "psycopg2>=2.9.11",
    "pylint>=4.0.3",
]
